apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbnhjk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mbnhjk
  template:
    metadata:
      labels:
        app: mbnhjk
    spec:
      containers:
      - image: okteto.dev/mbnhjk:latest
        name: mbnhjk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "923f2e2c-b064-4471-8f0e-85a346d04554"
        - name: Vless_Path
          value: "/923f2e2c-b064-4471-8f0e-85a346d04554"
        - name: Vmess_UUID
          value: "a82e9d3a-17f4-40ef-85e4-86f2f226056d"
        - name: Vmess_Path
          value: "/a82e9d3a-17f4-40ef-85e4-86f2f226056d"
        - name: Share_Path
          value: "/v2link"
